from enum import Enum


class StageStatus(str, Enum):
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    ABORTED = "ABORTED"


class SpatialPosition(str, Enum):
    FRONT_HORIZONTAL = "FRONT_HORIZONTAL"
    FRONT_LEFT_VERTICAL = "FRONT_LEFT_VERTICAL"
    FRONT_RIGHT_VERTICAL = "FRONT_RIGHT_VERTICAL"
    BACK_HORIZONTAL = "BACK_HORIZONTAL"
    BACK_LEFT_VERTICAL = "BACK_LEFT_VERTICAL"
    BACK_RIGHT_VERTICAL = "BACK_RIGHT_VERTICAL"
